/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: causelovesky (https://sketchfab.com/causelovesky)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sketch-vr-850eb8b4e45a4b4f9edb228f91d0eef7
Title: Sketch_VR
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import SpinOrbit from '../wrappers/SpinOrbit'

const Plane = (props) => {
    const { nodes, materials } = useGLTF('/models/plane.glb')
    return (
        <SpinOrbit center={props.position} radius={2.5} speed={1}>

        <group {...props} dispose={null}>
            <group position={[0, 9.96, 9.96]} rotation={[-Math.PI, 0, -Math.PI]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_2.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_3.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_4.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_5.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_6.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_7.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_8.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_9.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_10.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_11.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_12.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_13.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_14.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_15.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_16.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_17.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_18.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_19.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_20.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_21.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_22.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_23.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_24.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_25.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_26.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_27.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_28.geometry}
                    material={materials['0.ReflectiveMaterial']}
                />
            </group>
        </group>
        </SpinOrbit>
    )
}

useGLTF.preload('/models/plane.glb')

export default Plane;