/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: seyram14 (https://sketchfab.com/seyram14)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/road-rat-go-kart-957be8cbd0f443e3bef9c45ae062cc18
Title: Road Rat Go Kart
*/

import React, { useRef } from 'react'
import { useGLTF, OrbitControls } from '@react-three/drei'

const SpinningGoKart = (props) => {
    const { nodes, materials } = useGLTF('/models/go-kart2.glb')
    return (
        <group {...props} dispose={null}>
            <group scale={0.01}>
                <group scale={5.943}>
                    <group rotation={[-Math.PI / 2, 0, 0]}>
                        <group rotation={[-Math.PI / 2, 0, 0]}>
                            <OrbitControls />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh0.geometry}
                                material={materials.phongE1SG}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh1.geometry}
                                material={materials.phongE1SG}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh2.geometry}
                                material={materials.phongE1SG}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh3.geometry}
                                material={materials.phongE1SG}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh4.geometry}
                                material={materials.phongE2SG}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh5.geometry}
                                material={materials.phongE2SG}
                            />
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/go-kart2.glb')

export default SpinningGoKart;